spring:
  datasource:
    url: jdbc:h2:mem:preciosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console  # Para acceder a la consola H2: http://localhost:8080/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
      mode: always