openapi: 3.0.0
info:
  title: Servicio de Precios
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /prices:
    get:
      tags:
        - Price
      operationId: findFirstApplicablePrice
      summary: Obtener precio aplicable
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: applicationDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Precio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Error en la petición
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Precio no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error inesperado del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: base64
        brandId:
          type: integer
          format: base64
        priceList:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: double
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        details:
          type: string